Adaptive-Web-Community/Adaptive-Web-Components

package-lock.json
packages/adaptive-ui-explorer/package.json
packages/adaptive-ui/package.json

Clean up package version and sorting

Minor package cleanup

---

packages/adaptive-ui-explorer/package.json
packages/adaptive-ui/package.json
packages/adaptive-web-components/package.json

This update brings some new features and fixes for `fast-element` and `fast-foundation`.
Changelogs are linked, the more notable changes are CSS bindings in `fast-element` and fixes for `Picker`, `Slider`, and `DataGrid` in `fast-foundation`.
**Changelogs**
* [`fast-element`](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-element/CHANGELOG.md)
* [`fast-foundation`](https://github.com/microsoft/fast/blob/master/packages/web-components/fast-foundation/CHANGELOG.md)

feat: update to latest FAST

---

package-lock.json

Package lock file was out of sync.

Updated package lock per recent changes

---

examples/use-adaptive-components/package.json
package-lock.json

The previous version of `vite-plugin-svgo` had a dependency that caused problems with another dependency of Adaptive UI. The publisher has fixed this issue, so we can update to the latest.
[vite-plugin-svgo issue 1](https://github.com/r3dDoX/vite-plugin-svgo/issues/1)
Tested the example project. We can now safely use this plugin in other examples.

Updated svg plugin

---

.github/pull_request_template.md
.github/workflows/ci-validate-pr.yml
package.json

Updated PR template to include checklist item for running Beachball.

Added reminder to run beachball

---

README.md

Adding examples to the root level readme for better visibility. Each example has a link to its readme file and a button to launch it on stackblitz.

add examples to root readme

---

package-lock.json

Updates package lock from #62.

Update package lock from previous merge

---

change/@adaptive-web-adaptive-ui-0a6575e7-51d9-40de-8047-dae15516957c.json
packages/adaptive-ui/docs/api-report.md
packages/adaptive-ui/src/design-tokens/color.ts
packages/adaptive-ui/src/design-tokens/modules.ts

This PR just moves some code around to make a subsequent PR easier to understand. The diffs are a little strange, but the change is the sequence of blocks in `color.ts` and moving some helpers from `modules.ts`. One missing helper was added.

Update Adaptive UI code sequence (organization only)

---

change/@adaptive-web-adaptive-ui-7ad90905-59f2-4fc5-9466-accf27e11c77.json
packages/adaptive-ui-figma-designer/src/core/model.ts
packages/adaptive-ui-figma-designer/src/core/node.ts
packages/adaptive-ui-figma-designer/src/core/registry/custom-recipes.ts
packages/adaptive-ui-figma-designer/src/core/registry/design-token-registry.ts
packages/adaptive-ui-figma-designer/src/core/registry/recipes.ts
packages/adaptive-ui-figma-designer/src/figma/controller.ts
packages/adaptive-ui-figma-designer/src/figma/node.ts
packages/adaptive-ui-figma-designer/src/ui/app.ts
packages/adaptive-ui-figma-designer/src/ui/ui-controller.ts
packages/adaptive-ui/docs/api-report.md
packages/adaptive-ui/src/design-tokens/color.ts
packages/adaptive-ui/src/design-tokens/layer.ts

- Aligned plugin to new model where a token might have multiple uses
- Aligned token registration
- Cleanup of some component handling logic
- More comments
Related to #77
Remaining work on the related issue is to add support for style modules in the plugin.
There will be some cleanup on handling the `fillColor` token as well.

Designer token model update

---

.github/workflows/publish-packages.yml

This PR sets up a publish workflow that will bump version numbers and publish packages before writing the version changes back to the repository. This workflow will automatically get triggered when a new release tag is created in GitHub.

chore: add publish workflow

---

change/@adaptive-web-adaptive-ui-81d66b12-c2d3-448c-a461-f69df207ce7e.json
examples/customize-component/src/index.ts
packages/adaptive-ui/docs/api-report.md
packages/adaptive-ui/src/design-tokens/color.ts
packages/adaptive-ui/src/design-tokens/modules.ts
packages/adaptive-ui/src/index.ts
packages/adaptive-ui/src/modules/styles.ts
packages/adaptive-ui/src/token-helpers-color.ts

Moving some helper functions around, adding docs, and exporting them.
Tested in Storybook and Adaptive UI Explorer,

Export color token and style helpers

---

.github/workflows/publish-packages.yml

This PR fixes the publish workflow where it couldn't find the beachball command. It also only builds the two packages that actually get published instead of everything.

fix failures in publish workflow

---

change/@adaptive-web-adaptive-ui-0bd327ff-ef0c-4914-98f1-ef5bacf098b3.json
change/@adaptive-web-adaptive-ui-23ce4046-3241-426a-918b-cc361a6bfdff.json
change/@adaptive-web-adaptive-ui-46eea0a4-4401-4a9a-b0cb-dc3dfb1a9eac.json
change/@adaptive-web-adaptive-ui-52badea5-1494-4073-a335-ef8562470c5d.json
change/@adaptive-web-adaptive-ui-5a8c14e6-76e1-4b14-b0a1-5be5bd4ab774.json
change/@adaptive-web-adaptive-ui-6e0ca8ae-ac2d-4f40-806c-25a538f0a0ab.json
change/@adaptive-web-adaptive-ui-81d66b12-c2d3-448c-a461-f69df207ce7e.json
change/@adaptive-web-adaptive-ui-9cf489bb-f08c-4dbd-ab63-c0fc340423d2.json
change/@adaptive-web-adaptive-ui-c5541eb5-a043-4841-9783-4f449af6f27d.json
change/@adaptive-web-adaptive-ui-d2785b2f-53c0-4fc8-9293-f9bc0027c2ac.json
change/@adaptive-web-adaptive-ui-fc02451e-1a04-4f28-a159-53ede7af978f.json
change/@adaptive-web-adaptive-web-components-29c191a0-f10e-4247-83e5-59a516148022.json
change/@adaptive-web-adaptive-web-components-4c31d385-6717-4dd3-8117-df8317a12c6f.json
change/@adaptive-web-adaptive-web-components-4f880444-6134-4422-8d95-fad857235e9d.json
change/@adaptive-web-adaptive-web-components-9feaf463-744b-48f4-ac29-48a76f7c3144.json
change/@adaptive-web-adaptive-web-components-cb0d66f8-ea09-4e3b-96e0-40390e01607a.json
change/@adaptive-web-adaptive-web-components-fb405a21-d810-4012-8aa4-2d42fe336de4.json
examples/customize-component/package.json
examples/use-adaptive-components/package.json
package-lock.json
packages/adaptive-ui-explorer/package.json
packages/adaptive-ui-figma-designer/package.json
packages/adaptive-ui/CHANGELOG.json
packages/adaptive-ui/CHANGELOG.md
packages/adaptive-ui/package.json
packages/adaptive-web-components/CHANGELOG.json
packages/adaptive-web-components/CHANGELOG.md
packages/adaptive-web-components/package.json

publish packages

---

change/@adaptive-web-adaptive-web-components-26b9e0a6-29cf-4aaf-b82d-0e59321ea5ba.json
package-lock.json
packages/adaptive-web-components/docs/api-report.md
packages/adaptive-web-components/src/design-system.ts

This PR enables the `DesignSystem` interface to change the element prefix on definitions that get passed to it that have already been composed. 
Still working on refining the different export paths and the compose helpers for better ergonomics, but this change is a step in that direction.

feat: enable prefix changing for composed definitions through the `DesignSystem` interface

---

.github/workflows/publish-packages.yml

This PR attempts to fix the publish workflow so that it can be run via CI. It will still need to be tested with an actual publish and adjusted in case any other issues come up.

fix: fix the publish workflow failing to publish

---

.github/workflows/publish-packages.yml

trying some config tweaks to see if publishes will succeed.

fix: testing new ci config for publishing

---

change/@adaptive-web-adaptive-web-components-26b9e0a6-29cf-4aaf-b82d-0e59321ea5ba.json
examples/customize-component/package.json
examples/use-adaptive-components/package.json
package-lock.json
packages/adaptive-ui-figma-designer/package.json
packages/adaptive-web-components/CHANGELOG.json
packages/adaptive-web-components/CHANGELOG.md
packages/adaptive-web-components/package.json

This PR runs beachball bump manually due to this step failing in the last CI run.

chore: manual version bump from failed ci run

---

change/@adaptive-web-adaptive-web-components-c7bec1ba-d56a-48f6-83b6-398ec204dc0a.json
package-lock.json
packages/adaptive-ui-figma-designer/package.json
packages/adaptive-ui-figma-designer/src/core/registry/recipes.ts
packages/adaptive-web-components/docs/api-report.md

Added missing highlight base color to the Figma designer

Designer: Added missing highlight color

---

change/@adaptive-web-adaptive-ui-aba7bf21-ab6e-4125-afe4-e3217c1a28c3.json
packages/adaptive-ui-figma-designer/src/core/registry/recipes.ts
packages/adaptive-ui-figma-designer/src/figma/node.ts
packages/adaptive-ui-figma-designer/src/ui/app.ts
packages/adaptive-ui-figma-designer/src/ui/ui-controller.ts
packages/adaptive-ui/src/density/index.ts
packages/adaptive-ui/src/design-tokens/modules.ts

Added access to individual density design tokens and included in Figma designer.

Adaptive UI - Improve density support

---

change/@adaptive-web-adaptive-ui-5cbfb44a-0c65-4ea7-b11e-dfcca25a4960.json
change/@adaptive-web-adaptive-web-components-468d3c54-91d7-4cfd-a287-6681ccd5f766.json
package-lock.json
packages/adaptive-ui-explorer/package.json
packages/adaptive-ui-figma-designer/package.json
packages/adaptive-ui-figma-designer/src/ui/components/design-token-field/index.ts
packages/adaptive-ui/package.json
packages/adaptive-ui/src/adaptive-design-tokens.ts
packages/adaptive-ui/src/apply-mixins.ts
packages/adaptive-web-components/package.json

Updating FAST to latest versions

chore: update fast dependencies

---

change/@adaptive-web-adaptive-ui-e9b55f15-87f7-421e-95fe-f4d0380e715e.json
packages/adaptive-ui-figma-designer/src/core/registry/recipes.ts
packages/adaptive-ui-figma-designer/src/figma/node.ts
packages/adaptive-ui-figma-designer/src/ui/app.ts
packages/adaptive-ui-figma-designer/src/ui/components/corner-radius/index.ts
packages/adaptive-ui-figma-designer/src/ui/components/stealth-button/index.ts
packages/adaptive-ui-figma-designer/src/ui/components/token-glyph/index.ts
packages/adaptive-ui-figma-designer/src/ui/ui-controller.ts
packages/adaptive-ui/docs/api-report.md
packages/adaptive-ui/src/color/recipes/contrast-and-delta-swatch-set.ts
packages/adaptive-ui/src/color/recipes/delta-swatch-set.ts
packages/adaptive-ui/src/design-tokens/color.ts
packages/adaptive-ui/src/design-tokens/modules.ts
packages/adaptive-ui/src/modules/styles.ts

- Swapped default setting for transparent output from delta rules (useful for stealth, not other recipes)
- Added square density modifier
- Update outline modules to include fillColor
- Cleaned up density display naming
- Fixed nodes which could have padding
- Fixed corner radius only applying to top left
- Partial fix applying duplicate style modules
- Fixed color swatch display
Tested in Figma and Explorer
The controller model in the plugin needs to be refactored. I don't love all the changes in this PR, but they require a better binding model to fix better. Coming soon, time and priorities allowing.

A handful of fixes in the Designer

---

.vscode/settings.json
packages/adaptive-ui-figma-designer/src/ui/app.ts
packages/adaptive-ui-figma-designer/src/ui/components/design-tokens-form/index.ts
packages/adaptive-ui-figma-designer/src/ui/ui-controller-elements.ts
packages/adaptive-ui-figma-designer/src/ui/ui-controller-styles.ts
packages/adaptive-ui-figma-designer/src/ui/ui-controller-tokens.ts
packages/adaptive-ui-figma-designer/src/ui/ui-controller.ts

The UI controller class was responsible for three main things:
- Handling the mapping between nodes (layers in the design tool) and elements (for Adaptive UI evaluation)
- Managing design token value overrides
- Managing applied style modules or style tokens
Some doc comments added too!
The PR splits the controller into those three sections to make the code more maintainable.
Code has been moved and some minor renaming. Mostly the large controller class has been split into three additional classes/files.
There is one minor state update issues addressed at the bottom of `app.ts`.
 

Refactor the UI controller class

---

change/@adaptive-web-adaptive-ui-3eb0625b-478d-4cb3-8c51-0eede6dde439.json
packages/adaptive-ui/src/design-tokens/modules.ts
packages/adaptive-ui/src/modules/styles.ts

A copy/paste error caused a style to be overwritten. Added a check for this and fixed the issue.

Fix corner radius style not applying

---

change/@adaptive-web-adaptive-ui-3eb0625b-478d-4cb3-8c51-0eede6dde439.json
packages/adaptive-ui/src/design-tokens/modules.ts
packages/adaptive-ui/src/modules/styles.ts

I merged #144 into the wrong branch. This merges it to main instead.
A copy/paste error caused a style to be overwritten. Added a check for this and fixed the issue.

Fix corner radius style not applying (redo)

---

change/@adaptive-web-adaptive-ui-834cdbaa-9341-4063-a72b-f6ea2f1fe264.json
packages/adaptive-ui/src/design-tokens/color.ts

Adjust color deltas for more consistent behavior.

updates adaptive ui color deltas

---

change/@adaptive-web-adaptive-web-components-729a45f2-bc11-46dc-b00a-f15f7ebbd44c.json
packages/adaptive-web-components/.storybook/manager.mjs
packages/adaptive-web-components/src/components/checkbox/checkbox.styles.modules.ts
packages/adaptive-web-components/src/components/combobox/combobox.styles.ts
packages/adaptive-web-components/src/components/radio/radio.styles.modules.ts
packages/adaptive-web-components/src/components/switch/switch.styles.modules.ts

- Adjust small control label style
- Fix position issue on combobox
- Fix shortcut issue in Storybook
Tested in Storybook.

Component cleanup

---

change/@adaptive-web-adaptive-ui-0f4590a7-06cd-4556-921f-54831283c1dd.json
change/@adaptive-web-adaptive-web-components-1b25a35c-1ea0-4c2b-a03b-1514a5895a2a.json
packages/adaptive-ui/docs/api-report.md
packages/adaptive-ui/src/density/index.ts
packages/adaptive-web-components/docs/api-report.md
packages/adaptive-web-components/src/index.ts

- Convenience for setting padding in one property
- Default component styling
Additive only, no testable changes.

Added density and component styling helpers

---

package-lock.json
packages/adaptive-ui-explorer/index.html
packages/adaptive-ui-explorer/package.json
packages/adaptive-ui-explorer/src/app.ts
packages/adaptive-ui-explorer/src/components/adaptive-component.ts
packages/adaptive-ui-explorer/src/components/color-block.ts
packages/adaptive-ui-explorer/src/components/control-pane/control-pane.styles.ts
packages/adaptive-ui-explorer/src/components/control-pane/control-pane.template.ts
packages/adaptive-ui-explorer/src/components/control-pane/control-pane.ts
packages/adaptive-ui-explorer/src/components/layer-background/index.ts
packages/adaptive-ui-explorer/src/components/palette-gradient/palette-gradient.styles.ts
packages/adaptive-ui-explorer/src/components/style-example.ts
packages/adaptive-ui-explorer/src/components/swatch.ts
packages/adaptive-ui-explorer/src/index.ts
packages/adaptive-ui-explorer/src/state.ts

The Explorer app has been around for a while and doesn't use FAST / AWC to the full extent. Here are a few updates to better align:
- Migrated to state context object
- Migrated control panel to AWC
- Updated styling
Tested in Adaptive UI Explorer

Explorer updates:

---

change/@adaptive-web-adaptive-ui-cce85a67-4756-4a97-8313-d2c810defe53.json
packages/adaptive-ui-figma-designer/src/core/registry/recipes.ts
packages/adaptive-ui-figma-designer/src/figma/node.ts
packages/adaptive-ui-figma-designer/src/ui/app.ts
packages/adaptive-ui-figma-designer/src/ui/ui-controller-styles.ts
packages/adaptive-ui/src/density/index.ts

Updated density token settings for proper application and updated the Figma designer to enable applying individual density tokens.

Designer: Added support for applying individual density tokens

---

change/@adaptive-web-adaptive-ui-ff49c45e-e50b-4cae-ac86-69ccd40127a7.json
packages/adaptive-ui-figma-designer/src/core/registry/recipes.ts
packages/adaptive-ui-figma-designer/src/figma/node.ts
packages/adaptive-ui-figma-designer/src/figma/utility.ts
packages/adaptive-ui-figma-designer/src/ui/app.ts
packages/adaptive-ui/docs/api-report.md
packages/adaptive-ui/src/design-tokens/elevation.ts
packages/adaptive-ui/src/index.ts
packages/adaptive-ui/src/shadow/index.ts

Updated the Designer plugin to include shadow definitions and added support for creating in Figma.

Added shadows to Designer plugin

---

change/@adaptive-web-adaptive-ui-cf3e3da7-626e-49ec-ba1c-bab3c6461d40.json
packages/adaptive-ui/src/core/density/index.ts

Fix a sequence issue in the density helper that was created in #189.

Adaptive UI: Fix a sequence issue in the density helper

---

.github/CODEOWNERS
.github/workflows/publish-packages.yml

This is a maintenance pass on the CODEOWNERS file and adds @nicholasrice as a codeowner

chore: updates to repository settings

---

change/@adaptive-web-adaptive-ui-75f07927-6c24-47c5-8ebb-2ba36756e07d.json
packages/adaptive-ui-figma-designer/src/core/code-gen.ts
packages/adaptive-ui-figma-designer/src/figma/node.ts
packages/adaptive-ui-figma-designer/src/ui/app.ts
packages/adaptive-ui-figma-designer/src/ui/ui-controller-code.ts
packages/adaptive-ui/src/reference/modules.ts

Adds support for generating the anatomy definition code based on the Designer structure.

Designer: Added anatomy code generation

---

change/@adaptive-web-adaptive-ui-d99719c4-dff8-4914-b6c0-d96b4dee306c.json
change/@adaptive-web-adaptive-web-components-a8be2964-33b7-458e-af89-13dc4ee62eca.json
packages/adaptive-ui/docs/api-report.md
packages/adaptive-ui/src/core/modules/types.ts
packages/adaptive-web-components/docs/api-report.md
packages/adaptive-web-components/src/components/data-grid-cell/data-grid-cell.styles.modules.ts
packages/adaptive-web-components/src/components/data-grid-cell/data-grid-cell.template.ts
packages/adaptive-web-components/src/components/data-grid-row/data-grid-row.template.ts
packages/adaptive-web-components/src/components/divider/divider.styles.modules.ts
packages/adaptive-web-components/src/components/divider/divider.template.ts
packages/adaptive-web-components/src/components/flipper/flipper.template.ts
packages/adaptive-web-components/src/components/radio-group/radio-group.template.ts
packages/adaptive-web-components/src/components/skeleton/skeleton.styles.modules.ts
packages/adaptive-web-components/src/components/skeleton/skeleton.template.ts
packages/adaptive-web-components/src/components/slider-label/slider-label.template.ts
packages/adaptive-web-components/src/components/slider/slider.template.ts
packages/adaptive-web-components/src/components/tabs/tabs.template.ts
packages/adaptive-web-components/src/components/toolbar/toolbar.template.ts

Add improved structural support for multi-value string anatomy conditions like `shape` or `orientation`.
Splitting this from pending work to improve capabilities of Design-to-Code generation.

Adaptive UI: Add support for multi-value string anatomy conditions

---

packages/adaptive-ui-figma-designer/src/core/model.ts
packages/adaptive-ui-figma-designer/src/core/node.ts
packages/adaptive-ui-figma-designer/src/core/serialization.ts
packages/adaptive-ui-figma-designer/src/figma/controller.ts
packages/adaptive-ui-figma-designer/src/figma/main.ts
packages/adaptive-ui-figma-designer/src/figma/node.ts
packages/adaptive-ui-figma-designer/src/ui/index.ts
packages/adaptive-ui-figma-designer/src/ui/ui-controller.ts

Removes explicit serialization code and uses a replacer/reviver to revive Maps instead, which were the problematic data types.

Designer: Clean up message serialization

---

change/@adaptive-web-adaptive-ui-designer-figma-89eb51bf-e37c-4220-98b2-8d8b307e710c.json
change/@adaptive-web-adaptive-ui-fb42213d-30d8-4790-953d-d4c2c0ca31ac.json
packages/adaptive-ui-designer-figma/src/cli/main.ts
packages/adaptive-ui/package.json

This PR does two things:
1. Moves dependencies of `@adaptive-web/adaptive-ui` that are used as runtime dependencies into the 'dependencies' field from 'devDependencies'.
2. Removes undesirable console logging of the input PAT for the `aui-figma-compiler` CLI.

fix: Dependencies and PAT logging

---

change/@adaptive-web-adaptive-ui-bf3df06e-f531-43cb-b7ae-e33d9db259c8.json
change/@adaptive-web-adaptive-ui-designer-figma-ca51ff82-1a5d-4468-aaf8-73e9e81e15c7.json
packages/adaptive-ui-designer-figma/src/lib/anatomy.ts
packages/adaptive-ui/docs/api-report.md
packages/adaptive-ui/src/bin/aui.ts
packages/adaptive-ui/src/core/modules/types.ts

Fixes a few issues when running the AUI CLI.
Tested in the CLI

Adaptive UI: Anatomy CLI fixes

---

change/@adaptive-web-adaptive-ui-designer-figma-c4faed57-4c53-4767-b0eb-1c18daf9c8e6.json
change/@adaptive-web-adaptive-ui-e4bc13b2-9613-478b-943f-91caad3db43d.json
packages/adaptive-ui-designer-figma-plugin/src/core/code-gen.ts
packages/adaptive-ui-designer-figma-plugin/src/figma/node.ts
packages/adaptive-ui-designer-figma/src/cli/anatomy.ts
packages/adaptive-ui-designer-figma/src/cli/figma-rest-client.ts
packages/adaptive-ui-designer-figma/src/cli/main.ts
packages/adaptive-ui-designer-figma/src/lib/anatomy.ts
packages/adaptive-ui-designer-figma/src/lib/constants.ts
packages/adaptive-ui-designer-figma/src/lib/index.ts
packages/adaptive-ui-designer-figma/src/lib/node-parser.ts
packages/adaptive-ui/docs/api-report.md
packages/adaptive-ui/src/bin/aui.ts
packages/adaptive-ui/src/core/modules/types.ts

- Improved support for generating conditions
- Improved support for editing anatomy file
- Added individual components to the list (not sets)
- Other cleanup
Tested in Figma CLI

Adaptive UI: Improved Figma CLI

---

change/@adaptive-web-adaptive-ui-2baa1927-6a42-4da6-a58f-7b5457bb9dec.json
change/@adaptive-web-adaptive-ui-designer-figma-46ac51d1-29c2-42cb-8057-f9b7ce2c3643.json
packages/adaptive-ui-designer-figma/src/lib/anatomy.ts
packages/adaptive-ui/docs/api-report.md
packages/adaptive-ui/src/bin/aui.ts
packages/adaptive-ui/src/core/modules/element-styles-renderer.ts
packages/adaptive-ui/src/core/modules/selector.ts
packages/adaptive-ui/src/core/modules/types.ts

Fixes a few cases found while generating style sheets around focus and disabled rules.
Tested in the Figma CLI.

AUI: Fix global style generation

---

change/@adaptive-web-adaptive-ui-80cc5c2d-8bf8-4956-a470-183ea023604e.json
package-lock.json
packages/adaptive-ui/package.json
packages/adaptive-ui/src/bin/aui.ts

This PR introduces a process to merge CSS rules when transpiling a JSON anatomy to a .css file. It uses postcss and several merge-rule plugins to achieve the rule merging. 
This will help significantly reduce the volume of CSS generated from anatomies.

feat: CSS rules during CSS generation from JSON anatomy

---

change/@adaptive-web-adaptive-ui-3677b8f0-153b-48e9-b402-d50350e968f2.json
packages/adaptive-ui/src/core/modules/element-styles-renderer.ts

This PR re-orders the definition of interactivity CSS rules so that _active_ is defined after _focus_, allowing _active_ properties to override _focus_ properties. When _focus_ is defined last, properties of _focus_ can override properties of _active_, which can cause the _active_ state of a focused element to paint incorrectly (and not appear active at all).

fix: define active state styles after focus state

---

change/@adaptive-web-adaptive-ui-dda26682-04a9-49e9-abb3-c4c13a75350b.json
change/@adaptive-web-adaptive-ui-designer-core-848b0782-1e38-4b1d-9704-28611cffce60.json
change/@adaptive-web-adaptive-web-components-0a6dc60f-a996-4459-a2ab-6fa972eda308.json
examples/customize-component/src/index.ts
package-lock.json
packages/adaptive-ui-designer-core/src/registry/custom-recipes.ts
packages/adaptive-ui-designer-figma-plugin/src/ui/app.ts
packages/adaptive-ui/docs/api-report.md
packages/adaptive-ui/src/core/density/index.ts
packages/adaptive-ui/src/core/modules/element-styles-renderer.ts
packages/adaptive-ui/src/core/modules/styles.ts
packages/adaptive-ui/src/core/modules/types.ts
packages/adaptive-ui/src/migration/color.ts
packages/adaptive-ui/src/reference/appearance.ts
packages/adaptive-ui/src/reference/color.ts
packages/adaptive-ui/src/reference/modules.ts
packages/adaptive-web-components/src/components/progress/progress.styles.modules.ts
packages/adaptive-web-components/src/components/tooltip/tooltip.styles.modules.ts

Cleans up some functionality around shorthand for Style Properties.
Tested in Figma and AWC.
I know, this code needs tests :D

AUI: Improve StyleProperty shorthand capabilities

---

change/@adaptive-web-adaptive-ui-103db39c-c40d-4986-9b70-dfcf1c8c1ef9.json
packages/adaptive-ui/src/reference/modules.ts

Fixed a minor typo in a color recipe. Doesn't manifest in any different values.

AUI: Fix minor color recipe bug

---

package-lock.json
packages/adaptive-ui-designer-figma-plugin/package.json
packages/adaptive-ui-designer-figma-plugin/src/figma/node.ts

Updated Figma typings and removed a previously needed default value.

Designer: Updated Figma types

---

change/@adaptive-web-adaptive-ui-ad0b92ba-bcd2-46f0-b98b-80a5741b05a0.json
package-lock.json
packages/adaptive-ui/docs/api-report.md
packages/adaptive-ui/src/core/modules/css.ts
packages/adaptive-ui/src/core/modules/types.ts

Added support for layout wrapping in css styles.

AUI: Added layout wrap support

---

packages/adaptive-ui-designer-figma-plugin/src/core/messages.ts
packages/adaptive-ui-designer-figma-plugin/src/figma/controller.ts
packages/adaptive-ui-designer-figma-plugin/src/ui/app.ts
packages/adaptive-ui-designer-figma-plugin/src/ui/index.ts
packages/adaptive-ui-designer-figma-plugin/src/ui/ui-controller.ts

Added a couple of settings to the Designer plugin to give more control over processing to speed things up a bit.

Designer: Added some convenience settings
