packages/adaptive-ui-explorer/package.json, packages/adaptive-ui/src/design-tokens/color.ts
Update color recipes `DesignToken`s to include and intermediary `Value` token to track an evaluated color set.
The styling and token system requires css tokens for each color from a set like `rest`, `hover`, etc. The recipe that calculates the set is another token. In the current setup each css token causes the complete set to reevaluate and then only takes a single color from the set. The intermediary token now caches the complete value of the set and can provide values to subsequent colors from that set.
The same change is applied to all `InteractiveColorRecipe` tokens.
While I didn't see the performance change I had hoped for, at least I did not observe a drop in performance. I'll take that as good news to mean that the design system calculations are minimal, though I'd like to …
=> Optimize color recipe evaluation

change/@adaptive-web-adaptive-ui-a7fba9b9-4637-44fe-bbe8-525e6a6b464e.json, packages/adaptive-ui-explorer/package.json, packages/adaptive-ui-explorer/src/app.ts, packages/adaptive-ui-explorer/src/components/adaptive-component.ts, packages/adaptive-ui-explorer/src/components/color-block.ts, packages/adaptive-ui/src/color/recipes/black-or-white-by-contrast.spec.ts, packages/adaptive-ui/src/color/recipes/black-or-white-by-contrast.ts
In some cases, a less-contrasting foreground color might be returned. The `blackOrWhiteByContrast` recipe has an option for whether to force black as the foreground color if it passes. Otherwise it will default to white because that tends to be easier to read over an accent color. In some cases, particularly dark accent colors, if the preferred foreground color didn't pass min contrast the "other" color was returned, even though _that_ color might not pass the min contrast either.
Now it will return the highest contrasting color if neither meets the requirements.
Includes minor Adaptive UI Explorer fixes.
The other changes in the `adaptive-ui-explorer` package are minor formatting or consistency issues I ran into while working on this.
=> Fix black or white foreground recipe

change/@adaptive-web-adaptive-ui-5c23ca46-af72-4a7c-88fd-ccefcc81bd59.json, packages/adaptive-ui/docs/api-report.md, packages/adaptive-ui/src/color/recipe.ts, packages/adaptive-ui/src/design-tokens/color.ts
Updates the definition of the color `DesignToken`s to use some helper functions to tie the definitions together more. These tokens have been difficult to keep in sync because there are so many strings.
I tried to talk myself out of doing this change because the evolution is to move these to being generated, but as part of the evolution I need to rename some of the recipe sets, so I wanted to start here.
An update of [FAST 6238](https://github.com/microsoft/fast/pull/6238).
A lot of find and replace here. Same change for each recipe set.
Tested that the build worked and that the Storybook site looked correct.
The immediately following change will introduce semantic named color recipe sets that will be composed into functional styles that will maintain accessibility and design intent. These …
=> Restructure color recipe design token definition

packages/adaptive-ui-explorer/src/app.ts, packages/adaptive-ui-explorer/src/components/color-block.ts, packages/adaptive-ui-explorer/src/components/control-pane/control-pane.template.ts, packages/adaptive-ui-explorer/src/components/control-pane/control-pane.ts, packages/adaptive-ui/docs/api-report.md, packages/adaptive-ui/src/design-tokens/README.md, packages/adaptive-ui/src/design-tokens/color.ts, packages/adaptive-ui/src/styles.ts
This is part of the evolution of the design tokens, specifically the color recipes that will evolve to the default configuration.
The new doc file describes this in detail, but the intent is to create base recipes that can be combined into patterns to be applied to components. Typically (for color) this is fill, border, and text. What this intends to solve is the fact that once you have these patterns, many need to follow contrast requirements. For instance, you can't safely use only a "subtle" fill on a checkbox because it doesn't provide 3:1 contrast. So the intent is that the patterns can be built such that they follow accessibility guidelines, and then applied as desired.
I expect we can find overlap in the treatments and am hoping to define only the behaviors and mix that with the …
=> Updated to semantic color recipes and added WCAG contrast level support

change/@adaptive-web-adaptive-ui-d459eac4-9359-495a-94b6-db1b9e726274.json, change/@adaptive-web-adaptive-web-components-ca691012-4ca5-4f72-ae9e-ce28f0d7e6b6.json, packages/adaptive-ui-explorer/src/components/adaptive-component.ts, packages/adaptive-ui-explorer/src/components/color-block.ts, packages/adaptive-ui-explorer/src/components/style-example.ts, packages/adaptive-ui-explorer/src/components/swatch.ts, packages/adaptive-ui/docs/api-report.md, packages/adaptive-ui/src/color/recipe.ts, packages/adaptive-ui/src/design-tokens/color.ts, packages/adaptive-ui/src/design-tokens/index.ts, packages/adaptive-ui/src/design-tokens/modules.ts, packages/adaptive-ui/src/index.ts, packages/adaptive-ui/src/modules/element-styles-renderer.ts, packages/adaptive-ui/src/modules/index.ts, packages/adaptive-ui/src/modules/selector.ts, packages/adaptive-ui/src/modules/types.ts, packages/adaptive-ui/src/types.ts, packages/adaptive-web-components/src/components/anchor/anchor.compose.ts, packages/adaptive-web-components/src/components/anchor/anchor.styles.ts
This PR adds style modules, which consists of:
- Packaging color design tokens as sets and style modules
- Adding support for rendering style modules as ElementStyles
- Updating Adaptive UI Explorer to use style modules
- Updating Anchor to illustrate initial migration for components
This is based on #30 and represents the `style module` -> `component` relationship. It excludes the W3C token format parsing.
I'm particularly looking for clarity around the model and naming. I'll add docs and diagrams to support this, but:
- A "style module" is a reusable set of design decisions, illustrated so far as color sets like background, border, and foreground.
- A "renderer" is something that can turn a "style module" into rendered output. So far the only option is `ElementStyles`, but there could …
=> Add style modules

change/@adaptive-web-adaptive-ui-4e972827-718f-45be-b101-e9d54bf6899b.json, packages/adaptive-ui-explorer/src/app.ts, packages/adaptive-ui-explorer/src/components/color-block.ts, packages/adaptive-ui-explorer/src/components/swatch.ts, packages/adaptive-ui/docs/api-report.md, packages/adaptive-ui/src/design-tokens/README.md, packages/adaptive-ui/src/design-tokens/color.ts, packages/adaptive-ui/src/design-tokens/layer.ts, packages/adaptive-ui/src/design-tokens/modules.ts
- Renamed remaining "foreground" tokens
- Added support for derived foreground recipes over a background
- Moved deprecated tokens down
- Minor recipe tweaks and Explorer updates
In `color.ts` most of the change is moving the deprecated tokens to the bottom, but it doesn't diff correctly.
I tested in Explorer and Storybnook.
I'm going to update all components to use the modules like I did for the sample with Anchor.
=> Updated more color tokens and modules

change/@adaptive-web-adaptive-ui-8ba7e929-6e65-43aa-b8f8-2a29af929af9.json, packages/adaptive-ui-explorer/src/components/style-example.ts, packages/adaptive-ui/docs/api-report.md, packages/adaptive-ui/src/design-tokens/modules.ts, packages/adaptive-ui/src/modules/css.ts, packages/adaptive-ui/src/modules/element-styles-renderer.ts, packages/adaptive-ui/src/modules/selector.ts, packages/adaptive-ui/src/modules/types.ts, packages/adaptive-ui/src/types.ts, packages/adaptive-ui/tsconfig.json
The `Styles` definitions are intended to be a declarative representation of style decisions and not another form of css. For instance, other tech needs to be able to apply styles, like in Figma. We also need to be able to render the correct property, for instance, when a background fill might represent a solid color or a gradient which requires the `background-image` property in css.
Tested in Adaptive UI Explorer and Storybook. Does not feel like a large or complicated change.
Continued style module work.
=> Update Styles to typed StylesProperty key

change/@adaptive-web-adaptive-ui-5853f7b5-40b8-44f3-940d-399362cceae9.json, change/@adaptive-web-adaptive-web-components-ee19d797-05d2-4aee-853f-3c06bfff0cd4.json, packages/adaptive-ui/docs/api-report.md, packages/adaptive-ui/src/modules/types.ts, packages/adaptive-web-components/docs/api-report.md, packages/adaptive-web-components/src/components/checkbox/checkbox.compose.ts, packages/adaptive-web-components/src/components/checkbox/checkbox.definition.ts, packages/adaptive-web-components/src/components/checkbox/checkbox.styles.ts, packages/adaptive-web-components/src/components/checkbox/checkbox.template.ts, packages/adaptive-web-components/src/design-system.ts
Updates the style module pattern to fulfill the same requirements as the design system statics. That is, the aesthetic styles start to move into modules (colors for now) and they are registered during the default definition. 
I feel like this can be cleaned up, optimized, and more efficient. Looking for any thoughts in this regard, especially with defining component anatomy (parts, selectors, etc.)
Visual component testing in Storybook.
Continue to apply to remaining components.
=> Clean up style module definition

change/@adaptive-web-adaptive-ui-0e25b2fa-fbfd-400a-aeb2-0b107b41be45.json, change/@adaptive-web-adaptive-web-components-9c8db456-1c6f-4206-bb3a-8839633fc09b.json, packages/adaptive-ui-explorer/src/components/color-block.ts, packages/adaptive-ui/docs/api-report.md, packages/adaptive-ui/src/design-tokens/README.md, packages/adaptive-ui/src/design-tokens/color.ts, packages/adaptive-ui/src/design-tokens/modules.ts, packages/adaptive-web-components/src/components/checkbox/checkbox.definition.ts, packages/adaptive-web-components/src/components/radio/radio.styles.ts, packages/adaptive-web-components/src/components/slider/slider.styles.ts, packages/adaptive-web-components/src/components/switch/switch.styles.ts
Update "Perceivable" color recipes to "Discernible".
Perceivable identifies that something can be perceived, but does not convey the idea of clarity or distinction that we intend by these accessible color recipes.
This is one big find and replace.
Tested the Explorer site and Storybook.
=> Renamed `perceivable` colors to `discernible`

change/@adaptive-web-adaptive-ui-68e8e03e-6a83-4f42-acfd-d32ac1791795.json, change/@adaptive-web-adaptive-web-components-45ec4d64-27db-48f6-b201-997549877931.json, packages/adaptive-ui-explorer/src/components/color-block.ts, packages/adaptive-ui/docs/api-report.md, packages/adaptive-ui/src/color/recipe.ts, packages/adaptive-ui/src/color/recipes/contrast-and-delta-swatch-set.ts, packages/adaptive-ui/src/color/recipes/delta-swatch-set.ts, packages/adaptive-ui/src/color/swatch.ts, packages/adaptive-ui/src/color/utilities/conditional.ts, packages/adaptive-ui/src/design-tokens/README.md, packages/adaptive-ui/src/design-tokens/color.ts, packages/adaptive-ui/src/design-tokens/modules.ts, packages/adaptive-web-components/src/components/anchor/anchor.styles.ts, packages/adaptive-web-components/src/components/checkbox/checkbox.definition.ts
#54 introduced the concept of semantic color recipes, associating accessible contrast requirements with component usage patterns. At that time I identified the patterns that exist, but only migrated existing recipes to the new pattern names.
This PR adds the remaining patterns and recipes identified there. It also builds the associated foundational style modules.
I tried to make the diff easier to understand (#68) but it still isn't lining up correctly.
One of the most significant changes might be consolidating the delta tokens. As I was introducing new patterns, duplicated for accent and neutral palettes, I wanted to incorporate another systems aspect that the decision around the variation in color between the interactive states could be consolidated. This will help with a future update …
=> Finish semantic color recipe system and foundation style modules

.github/workflows/auto-assign.yml
GitHub validation failing with:
(node:1656) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Updating to latest to see if that helps.
=> Update auto-assign version

packages/adaptive-ui-figma-designer/src/core/controller.ts, packages/adaptive-ui-figma-designer/src/core/model.ts, packages/adaptive-ui-figma-designer/src/core/serialization.ts, packages/adaptive-ui-figma-designer/src/figma/controller.ts, packages/adaptive-ui-figma-designer/src/figma/node.ts, packages/adaptive-ui-figma-designer/src/ui/ui-controller.ts
The Designer plugin previously stored all applied design tokens (style attributes and values) is a single property. This included any styles that were inherited because they needed to be evaluated and pushed back to the design tool.
This accounted for a complexity in the Figma plugin data model, but as the style application model is becoming more complex, this complexity further hides what's going on.
Also includes some logging and doc updates.
This will be followed by a PR that adds support for applying style modules in the Designer.
=> Designer: Separate effective applied tokens

change/@adaptive-web-adaptive-ui-5a8c14e6-76e1-4b14-b0a1-5be5bd4ab774.json, change/@adaptive-web-adaptive-web-components-4f880444-6134-4422-8d95-fad857235e9d.json, packages/adaptive-ui-explorer/src/components/style-example.ts, packages/adaptive-ui-figma-designer/src/core/controller.ts, packages/adaptive-ui-figma-designer/src/core/model.ts, packages/adaptive-ui-figma-designer/src/core/node.ts, packages/adaptive-ui-figma-designer/src/core/registry/recipes.ts, packages/adaptive-ui-figma-designer/src/core/serialization.ts, packages/adaptive-ui-figma-designer/src/figma/node.ts, packages/adaptive-ui-figma-designer/src/ui/app.ts, packages/adaptive-ui-figma-designer/src/ui/ui-controller.ts, packages/adaptive-ui/docs/api-report.md, packages/adaptive-ui/src/design-tokens/modules.ts, packages/adaptive-ui/src/modules/element-styles-renderer.ts, packages/adaptive-ui/src/modules/styles.ts, packages/adaptive-web-components/src/components/accordion-item/accordion-item.styles.modules.ts, packages/adaptive-web-components/src/components/badge/badge.styles.modules.ts, packages/adaptive-web-components/src/components/breadcrumb-item/breadcrumb-item.styles.modules.ts, packages/adaptive-web-components/src/components/card/card.styles.modules.ts, packages/adaptive-web-components/src/components/combobox/combobox.styles.modules.ts, packages/adaptive-web-components/src/components/data-grid-cell/data-grid-cell.styles.modules.ts, packages/adaptive-web-components/src/components/disclosure/disclosure.styles.modules.ts, packages/adaptive-web-components/src/components/listbox/listbox.styles.modules.ts, packages/adaptive-web-components/src/components/menu/menu.styles.modules.ts, packages/adaptive-web-components/src/components/picker-menu/picker-menu.styles.modules.ts, packages/adaptive-web-components/src/components/picker/picker.styles.modules.ts, packages/adaptive-web-components/src/components/search/search.styles.modules.ts, packages/adaptive-web-components/src/components/select/select.styles.modules.ts, packages/adaptive-web-components/src/components/tab-panel/tab-panel.styles.modules.ts, packages/adaptive-web-components/src/components/tooltip/tooltip.styles.modules.ts
Adds support for applying and evaluating style modules in the Figma Designer plugin.
Closes #77 
I split the change into two commits. The first updates the style modules API to support naming. The second updates the plugin portion.
Basic style modules work, but I need to do some cleanup on some of the base style definitions and some UI enhancements.
=> Designer: add style module support

change/@adaptive-web-adaptive-ui-9cf489bb-f08c-4dbd-ab63-c0fc340423d2.json, change/@adaptive-web-adaptive-web-components-9feaf463-744b-48f4-ac29-48a76f7c3144.json, examples/customize-component/src/index.ts, package-lock.json, packages/adaptive-ui-explorer/src/components/style-example.ts, packages/adaptive-ui-figma-designer/package.json, packages/adaptive-ui-figma-designer/src/core/registry/custom-recipes.ts, packages/adaptive-ui-figma-designer/src/figma/node.ts, packages/adaptive-ui-figma-designer/src/ui/app.ts, packages/adaptive-ui-figma-designer/src/ui/ui-controller.ts, packages/adaptive-ui/docs/api-report.md, packages/adaptive-ui/src/design-tokens/appearance.ts, packages/adaptive-ui/src/design-tokens/color.ts, packages/adaptive-ui/src/design-tokens/modules.ts, packages/adaptive-ui/src/modules/css.ts, packages/adaptive-ui/src/modules/styles.ts, packages/adaptive-ui/src/modules/types.ts, packages/adaptive-web-components/src/components/accordion-item/accordion-item.styles.modules.ts, packages/adaptive-web-components/src/components/accordion-item/accordion-item.styles.ts, packages/adaptive-web-components/src/components/accordion/accordion.styles.modules.ts, packages/adaptive-web-components/src/components/accordion/accordion.styles.ts, packages/adaptive-web-components/src/components/data-grid-row/data-grid-row.styles.modules.ts, packages/adaptive-web-components/src/components/data-grid-row/data-grid-row.styles.ts, packages/adaptive-web-components/src/components/divider/divider.styles.modules.ts, packages/adaptive-web-components/src/components/divider/divider.styles.ts, packages/adaptive-web-components/src/components/listbox/listbox.styles.modules.ts, packages/adaptive-web-components/src/components/progress/progress.styles.modules.ts, packages/adaptive-web-components/src/components/progress/progress.styles.ts, packages/adaptive-web-components/src/components/tooltip/tooltip.styles.modules.ts
- Updates compound properties like `padding`, `border-*`, etc. into individual properties.
- Added support for evaluating `calc` statements like found on `padding` for use in Figma.
I was planning on individual properties to better support different tokens. When I got into implementing this, the model I ended up with here proved to be the simplest and best supported individual overrides.
CSS allows specifying many properties like `padding: top right bottom left`, but in this context that completely changed the shape and API of the merging and evaluating of styles that are composed together. It significantly complicated the logic in the plugin as well for the same reason.
One of the goals of the style module renderers is to encapsulate the complexity of CSS, so that's the appropriate place …
=> Update compound properties (padding, border, etc.)

change/@adaptive-web-adaptive-ui-c5541eb5-a043-4841-9783-4f449af6f27d.json, change/@adaptive-web-adaptive-web-components-29c191a0-f10e-4247-83e5-59a516148022.json, packages/adaptive-ui/docs/api-report.md, packages/adaptive-ui/src/styles.ts, packages/adaptive-web-components/src/components/anchor/anchor.styles.ts, packages/adaptive-web-components/src/components/avatar/avatar.styles.ts, packages/adaptive-web-components/src/components/breadcrumb-item/breadcrumb-item.styles.ts, packages/adaptive-web-components/src/components/button/button.styles.ts, packages/adaptive-web-components/src/components/card/card.styles.ts, packages/adaptive-web-components/src/components/checkbox/checkbox.styles.ts, packages/adaptive-web-components/src/components/combobox/combobox.styles.ts, packages/adaptive-web-components/src/components/data-grid-row/data-grid-row.styles.ts, packages/adaptive-web-components/src/components/divider/divider.styles.ts, packages/adaptive-web-components/src/components/listbox-option/listbox-option.styles.ts, packages/adaptive-web-components/src/components/listbox/listbox.styles.ts, packages/adaptive-web-components/src/components/menu-item/menu-item.styles.ts, packages/adaptive-web-components/src/components/number-field/number-field.styles.ts, packages/adaptive-web-components/src/components/picker-list-item/picker-list-item.styles.ts, packages/adaptive-web-components/src/components/picker-list/picker-list.styles.ts, packages/adaptive-web-components/src/components/picker-menu-option/picker-menu-option.styles.ts, packages/adaptive-web-components/src/components/picker-menu/picker-menu.styles.ts, packages/adaptive-web-components/src/components/radio/radio.styles.ts, packages/adaptive-web-components/src/components/search/search.styles.ts, packages/adaptive-web-components/src/components/select/select.styles.ts, packages/adaptive-web-components/src/components/switch/switch.styles.ts, packages/adaptive-web-components/src/components/tab/tab.styles.ts, packages/adaptive-web-components/src/components/text-area/text-area.styles.ts, packages/adaptive-web-components/src/components/text-field/text-field.styles.ts, packages/adaptive-web-components/src/components/tooltip/tooltip.styles.ts, packages/adaptive-web-components/src/components/tree-item/tree-item.styles.ts
The way the design tokens apply to elements it's proven to be beneficial to use `border-box` sizing so padding and border size is included in any width or height settings.
This change makes that standard and consistent in the base styles used by all components by default. The selector is setup to allow overriding back to `content-box` should there be a need.
Tested in Storybook.
=> Update styles to normalize to `border-box` sizing

change/@adaptive-web-adaptive-ui-46eea0a4-4401-4a9a-b0cb-dc3dfb1a9eac.json, change/@adaptive-web-adaptive-web-components-cb0d66f8-ea09-4e3b-96e0-40390e01607a.json, packages/adaptive-ui-figma-designer/src/core/registry/custom-recipes.ts, packages/adaptive-ui/docs/api-report.md, packages/adaptive-ui/src/color/recipe.ts, packages/adaptive-ui/src/design-tokens/color.ts, packages/adaptive-ui/src/design-tokens/layer.ts, packages/adaptive-ui/src/design-tokens/modules.ts, packages/adaptive-ui/src/elevation/recipe.ts, packages/adaptive-ui/src/recipes.ts, packages/adaptive-web-components/src/components/tree-item/tree-item.styles.ts
This follows #54 and #69 regarding semantic color recipes. The base recipes have been updated to be configured without a Palette, and the Recipe structure has been updated to allow derivative configurations, like using the same underlying recipe for accent and neutral palettes.
I chose to break the current optional `reference` `Swatch` in favor of the extension model for color config because it simplified the creation of the various tokens. I feel this is a better long term approach, however I did not follow the `object` model when updating elevation. Right now I feel that system is too simple to require it, but perhaps we will revisit when I get to migrating that to modules.
Tested in Adaptive UI Explorer and Storybook.
Adding a third palette for selection/highlight.
=> Adaptive UI: Formalized `Recipe` structure to enable better composition

change/@adaptive-web-adaptive-ui-52badea5-1494-4073-a335-ef8562470c5d.json, packages/adaptive-ui/src/density/index.ts, packages/adaptive-ui/src/design-tokens/appearance.ts, packages/adaptive-ui/src/design-tokens/color.ts, packages/adaptive-ui/src/design-tokens/elevation.ts, packages/adaptive-ui/src/design-tokens/index.ts, packages/adaptive-ui/src/design-tokens/layer.ts, packages/adaptive-ui/src/design-tokens/modules.ts, packages/adaptive-ui/src/design-tokens/palette.ts, packages/adaptive-ui/src/design-tokens/type.ts, packages/adaptive-ui/src/index.ts, packages/adaptive-ui/src/token-helpers.ts
Moved the token helper functions out from the directory with the reference tokens to formalize the distinction and in preparation for #104.
This PR is all about moving code, no functionality or export change. The largest diff is in `color.ts` where I renamed the helper functions and moved the base recipes up with their deltas. Note that in #105 the semantic recipes were made generic so they can work with any palette.
Migrate color token helpers out of the `design-tokens` directory and export them.
=> Adaptive UI: Token helpers cleanup

change/@adaptive-web-adaptive-ui-23ce4046-3241-426a-918b-cc361a6bfdff.json, packages/adaptive-ui-figma-designer/src/core/registry/recipes.ts, packages/adaptive-ui/docs/api-report.md, packages/adaptive-ui/src/adaptive-design-tokens.ts, packages/adaptive-ui/src/color/recipe.ts, packages/adaptive-ui/src/color/recipes/black-or-white-by-contrast-set.ts, packages/adaptive-ui/src/design-tokens/color.ts, packages/adaptive-ui/src/index.ts, packages/adaptive-ui/src/modules/styles.ts, packages/adaptive-ui/src/token-helpers-color.ts, packages/adaptive-ui/src/token-helpers.ts, packages/adaptive-ui/src/types.ts
Improved the way color recipes are created by chaining the token typed metadata. This makes the base recipes even more reusable since semantically a given recipe is always intended for a single use, like background fill or foreground fill.
Builds upon #105 and #106.
This work precedes adding the highlight color palette.
=> Improved typing and metadata on color recipes

packages/adaptive-ui-figma-designer/src/core/controller.ts, packages/adaptive-ui-figma-designer/src/core/model.ts, packages/adaptive-ui-figma-designer/src/core/node.ts, packages/adaptive-ui-figma-designer/src/core/serialization.ts, packages/adaptive-ui-figma-designer/src/figma/node.ts, packages/adaptive-ui-figma-designer/src/ui/ui-controller.ts
Adaptive UI is mostly about composing design tokens to style your components, but sometimes all you need is a simple value. This update fixes the plumbing so that values provided for style targets don't have to be tokens. If a string value is provided it will be passed to the style renderer as-is.
Renamed the evaluated design tokens to make it more clear that they weren't always tokens.
Tested in Figma Designer.
=> Designer: Updated style value model to support fixed values

change/@adaptive-web-adaptive-web-components-c04ae354-a56c-4f7d-9083-4b10f9b7d4cb.json, packages/adaptive-web-components/src/components/select/select.styles.ts
The inner control of the select component would not resize according to the width of the outer component.  This change sets the width of the inner control to 100% so authors can control the width of the select.
=> fix:  select inner control width

change/@adaptive-web-adaptive-web-components-f7feeb4e-447d-44bc-afae-280f0e7eb583.json, packages/adaptive-web-components/src/components/number-field/number-field.styles.ts, packages/adaptive-web-components/src/components/text-field/text-field.styles.ts
Added 100% width to styles for text field and number field inner controls as they were not tracking the parent component width changes.
ad-hoc
@bheston - should this be part of a module style instead?
=> fix: inner control of text/number fields not tracking component width

change/@adaptive-web-adaptive-web-components-0de560ad-b55b-48a1-b602-f7e4436daebe.json, packages/adaptive-web-components/src/components/picker-list/picker-list.styles.modules.ts, packages/adaptive-web-components/src/components/picker-list/picker-list.styles.ts
Picker with no selected items was shorter than with selected items.  With this change picker maintains a constant height regardless of whether items are selected or not.
ad hoc
- [ x] I have read the [CONTRIBUTING](https://github.com/adaptive-web/adaptive-web-components/blob/master/CONTRIBUTING.md) documentation for this project.
=> fix: picker gets taller when items selected

.vscode/settings.json, change/@adaptive-web-adaptive-ui-49a1a1c3-cb47-4350-a4e7-ed80ccaeb2eb.json, package-lock.json, packages/adaptive-ui-explorer/src/components/adaptive-component.ts, packages/adaptive-ui/docs/api-report.md, packages/adaptive-ui/package.json, packages/adaptive-ui/src/color/index.ts, packages/adaptive-ui/src/color/palette-okhsl.ts, packages/adaptive-ui/src/design-tokens/palette.ts
Updated the color palette logic to use the OKHSL color model. OK is a new-ish perceptual color system that improves upon LAB in a few ways. The HSL variation maps the coordinates to the familiar HSL model, but the perceptual aspect means it produces more human accurate results than the RGB model.
Here is a comparison of the old palettes to the new:
And here is the Microsoft default blue:
The new palette is more of the fade to white and black and doesn't produce as much hue and saturation shift. It's not as differentiated in the dark end as the old model, but that's a subjective opinion based on my screen and lighting conditions, etc.
Notice also in the palettes that the source color is marked with a `~` in the old palette meaning it's approximate, and a `⚬` in the new one indicating an …
=> Adaptive UI - Updated color palette based on okhsl

change/@adaptive-web-adaptive-ui-225efc1f-77b4-4221-bde7-3e390f91e404.json, packages/adaptive-ui-figma-designer/src/core/model.ts, packages/adaptive-ui-figma-designer/src/core/node.ts, packages/adaptive-ui-figma-designer/src/figma/node.ts, packages/adaptive-ui-figma-designer/src/ui/ui-controller.ts, packages/adaptive-ui/src/color/palette-okhsl.ts, packages/adaptive-ui/src/color/recipes/contrast-and-delta-swatch-set.ts, packages/adaptive-ui/src/color/recipes/delta-swatch-set.ts, packages/adaptive-ui/src/color/swatch.ts, packages/adaptive-ui/src/color/utilities/conditional.ts
This PR finally resolves an issue that has existed for a long time regarding evaluating colors based on the container fill color. Most color recipes use the `fill-color` token as an input, but chaining this down is complicated. It's been causing flipping of recipes where one time it's based on the container and next time it's based on itself. This finally resolves the issue by passing the container color as the context and letting a recipe evaluate with that context on the child element. Note that this is different in Figma than the way it works in code, but in code this is one of the reasons the style modules work the way they do with background / foreground color sets.
I added a comment to this in this code as well.
Basically what I said above. This has long been a complicated issue and …
=> Designer - Fix the fill color evaluation

change/@adaptive-web-adaptive-ui-e3098e7a-5d85-4d96-a94a-e749705ad9bf.json, change/@adaptive-web-adaptive-web-components-ac53355b-9197-4617-a00d-9fa90edbb090.json, packages/adaptive-ui-figma-designer/src/core/registry/recipes.ts, packages/adaptive-ui-figma-designer/src/ui/app.ts, packages/adaptive-ui-figma-designer/src/ui/ui-controller-styles.ts, packages/adaptive-ui/docs/api-report.md, packages/adaptive-ui/src/adaptive-design-tokens.ts, packages/adaptive-ui/src/density/index.ts, packages/adaptive-ui/src/design-tokens/color.ts, packages/adaptive-ui/src/design-tokens/modules.ts, packages/adaptive-web-components/src/components/button/button.styles.ts
- Removed subtle stroke from subtle fill styles
- Fixed border style handling
- Added WCAG contrast token to Designer
Temporary solution to better address the separation of border color and thickness from adjusting density based on the border thickness. Density now assumes border is specified as the safest way to decouple them.
=> Small Adaptive UI and Designer fixes

packages/adaptive-ui-figma-designer/src/core/controller.ts, packages/adaptive-ui-figma-designer/src/core/registry/recipes.ts, packages/adaptive-ui-figma-designer/src/figma/node.ts, packages/adaptive-ui-figma-designer/src/ui/app.ts, packages/adaptive-ui-figma-designer/src/ui/ui-controller-styles.ts, packages/adaptive-ui-figma-designer/src/ui/ui-controller.ts
Added support for removing styling when an applied style or token is removed from a node.
Previously when you applied a style or token, the visual change would be applied to the node in Figma, but when you removed the style or token the visual implications of it would remain. This created more of a "detach" than "remove" function, and we generally don't want visual artifacts not attached to styling behaviors hanging around.
=> Designer: Added remove support for styles and tokens

change/@adaptive-web-adaptive-ui-dcb49912-a53a-4289-bbd2-b5117bafc451.json, change/@adaptive-web-adaptive-web-components-1f3a9607-2e82-49c5-b7ba-ba9de8f9d63d.json, packages/adaptive-ui/docs/api-report.md, packages/adaptive-ui/src/adaptive-design-tokens.ts, packages/adaptive-ui/src/color/recipe.ts, packages/adaptive-ui/src/color/recipes/black-or-white-by-contrast-set.ts, packages/adaptive-ui/src/color/recipes/ideal-color-delta-swatch-set.spec.ts, packages/adaptive-ui/src/color/utilities/opacity.ts, packages/adaptive-ui/src/design-tokens/color.ts, packages/adaptive-ui/src/design-tokens/layer.ts, packages/adaptive-ui/src/design-tokens/modules.ts, packages/adaptive-ui/src/design-tokens/palette.ts, packages/adaptive-ui/src/migration/color.ts, packages/adaptive-ui/src/modules/element-styles-renderer.ts, packages/adaptive-ui/src/modules/styles.ts, packages/adaptive-ui/src/token-helpers-color.ts, packages/adaptive-ui/src/token-helpers.ts, packages/adaptive-web-components/src/components/tree-item/tree-item.styles.ts
While migrating focus state to Styles (#82), I found that requiring all states on an interactive set is too constrained for some purposes, including focus-only treatment. I started to run into this when adding disabled state as well (#91).
The value of a `DesignToken` can be null, though this isn't reflected in typing of the API. This update makes this capability clear in the typing of Adaptive UI.
There are different requirements depending on whether the interactive set is of tokens or values. Tokens can not be null in order to be referenced in `css` blocks. Token _values_ may actually be null, and a recipe may choose to return a null value.
Related issues linked above.
Tested in Storybook.
I believe the typing of the color recipes can be cleaned up a bit more. I will look into this …
=> Updated color recipes to allow null interactive states

change/@adaptive-web-adaptive-ui-be94cfb8-7fcd-465e-a89d-1fb7a1c82d9d.json, change/@adaptive-web-adaptive-web-components-53b24c53-96a4-443f-b5f0-1b5f51768892.json, packages/adaptive-ui/src/modules/element-styles-renderer.ts, packages/adaptive-web-components/src/components/accordion-item/accordion-item.styles.ts, packages/adaptive-web-components/src/components/anchor/anchor.styles.ts, packages/adaptive-web-components/src/components/avatar/avatar.styles.ts, packages/adaptive-web-components/src/components/badge/badge.styles.ts, packages/adaptive-web-components/src/components/breadcrumb-item/breadcrumb-item.styles.ts, packages/adaptive-web-components/src/components/button/button.styles.ts, packages/adaptive-web-components/src/components/calendar/calendar.styles.ts, packages/adaptive-web-components/src/components/checkbox/checkbox.styles.ts, packages/adaptive-web-components/src/components/combobox/combobox.styles.ts, packages/adaptive-web-components/src/components/data-grid-cell/data-grid-cell.styles.ts, packages/adaptive-web-components/src/components/flipper/flipper.styles.ts, packages/adaptive-web-components/src/components/listbox-option/listbox-option.styles.ts, packages/adaptive-web-components/src/components/menu-item/menu-item.styles.ts, packages/adaptive-web-components/src/components/number-field/number-field.styles.ts, packages/adaptive-web-components/src/components/picker-list-item/picker-list-item.styles.ts, packages/adaptive-web-components/src/components/picker-list/picker-list.styles.ts, packages/adaptive-web-components/src/components/picker-menu-option/picker-menu-option.styles.ts, packages/adaptive-web-components/src/components/radio/radio.styles.ts, packages/adaptive-web-components/src/components/search/search.styles.ts, packages/adaptive-web-components/src/components/select/select.styles.ts, packages/adaptive-web-components/src/components/tab/tab.styles.ts, packages/adaptive-web-components/src/components/text-field/text-field.styles.ts, packages/adaptive-web-components/src/components/tree-item/tree-item.styles.ts
Removing use of `fill` in the custom css styles for the components. This now sets the `fill` property whenever the foreground `color` is set.
Related to #79
Style files remove most uses of `currentcolor`. The remaining ones are for colors not set from Styles, should be resolved with the next style pass.
Tested in Storybook.
As commented, this is a stopgap solution and would be better implemented with the plugin architecture of the style generation.
=> Added support for setting `fill` when `color` is set

package-lock.json, packages/adaptive-ui-figma-designer/package.json, packages/adaptive-ui-figma-designer/src/core/model.ts, packages/adaptive-ui-figma-designer/src/core/node.ts, packages/adaptive-ui-figma-designer/src/figma/controller.ts, packages/adaptive-ui-figma-designer/src/figma/main.ts, packages/adaptive-ui-figma-designer/src/figma/node.ts, packages/adaptive-ui-figma-designer/src/ui/app.ts, packages/adaptive-ui-figma-designer/src/ui/index.ts, packages/adaptive-ui-figma-designer/src/ui/ui-controller-states.ts, packages/adaptive-ui-figma-designer/src/ui/ui-controller.ts
In the Figma Designer, a new feature when you select a component state, to create the interactive state variants automatically (hover, active, focus, and disabled).
A portion of this work updates the messaging model between the plugin and the UI. Previously we only had one type of message, which was component styling state back and forth. Updated to support multiple types of messages and added a new one for the "create states" message.
I think I can clean up the need to manage the serialization by removing the use of maps. Everything else should serialize correctly by default.
=> Designer: Added feature to create interactive component states

change/@adaptive-web-adaptive-ui-73e391e4-8d30-43d4-adb3-e25f35e09723.json, packages/adaptive-ui/docs/api-report.md, packages/adaptive-ui/src/color/palette-okhsl.ts
Updates the `culori` imports to use the path that supports tree-shaking.
I missed doing this on the initial PR.
Tested in one of the example apps.
Took 22k off the minimized size, 44k off the non minimized size.
=> Adaptive UI: Update culori imports for tree shaking

.vscode/settings.json, change/@adaptive-web-adaptive-ui-d998460b-6962-454f-b19c-e2d7d55ff826.json, packages/adaptive-ui-figma-designer/package.json, packages/adaptive-ui-figma-designer/src/core/node.ts, packages/adaptive-ui-figma-designer/src/core/registry/recipes.ts, packages/adaptive-ui-figma-designer/src/figma/controller.ts, packages/adaptive-ui-figma-designer/src/figma/node.ts, packages/adaptive-ui-figma-designer/src/ui/app.ts, packages/adaptive-ui-figma-designer/src/ui/ui-controller-elements.ts, packages/adaptive-ui-figma-designer/src/ui/ui-controller.ts, packages/adaptive-ui/src/design-tokens/color.ts, packages/adaptive-ui/src/design-tokens/modules.ts
As part of #156 an interactive component set gets a "focus" state. A common treatment for focus is the css `outline` property. Figma currently doesn't support this treatment, and the best way to accomplish it is to nest an edge-to-edge constrained element _within_ the element for which it represents focus. Since it actually draws outside of that element, the context for color recipes should be the parent of the focused element, but since in Figma it must be nested within, it picks up the context of the element itself.
This PR adds support for special handling for a layer named "Focus indicator" which relocates it to the correct parent.
Related to this, it adds a new focus recipe based on a palette (rather than black or white) to enable more subtle or customized focus treatments. The …
=> Designer: Fix containment issue with focus indicators in Figma.

change/@adaptive-web-adaptive-ui-af78f269-705d-4753-a2cf-fa5d40c26969.json, packages/adaptive-ui-explorer/src/components/color-block.ts, packages/adaptive-ui/src/design-tokens/color.ts, packages/adaptive-ui/src/design-tokens/modules.ts
Added color recipes which apply the `subtle` delta values, but in inverse to the context color. One common example of this usage is where action components like Button appear as a subtle fill darker than the container, and input components like Text Field appear lighter.
Also applied to the default input treatment and separated the base input style rules out to allow for overriding.
Additive color recipes.
Tested in Adaptive UI Explorer
=> Added subtle inverse color recipes

change/@adaptive-web-adaptive-ui-c5d3789b-ade6-4ff6-9e68-549c300e6d65.json, change/@adaptive-web-adaptive-web-components-4677862c-945e-4bc2-9156-9482acc69604.json, package-lock.json, packages/adaptive-ui/bin/adaptive-ui-build-styles.js, packages/adaptive-ui/docs/api-report.md, packages/adaptive-ui/package.json, packages/adaptive-ui/src/adaptive-ui-build-styles.ts, packages/adaptive-ui/src/install-dom-shim.ts, packages/adaptive-ui/tsconfig.json, packages/adaptive-web-components/package.json
Runtime styling is very flexible, but for zero performance impact we want to be able to generated css at build time. This is the start of the capability to do so, rendering the same styles which would be rendered at runtime using a CLI build script.
Note that currently this does not swap out the import references to the dynamic styles, it only generates the output css.
Tested against AWC package configuration. Needs more flexibility to work for other setups.
=> Adaptive UI: Added styles build script

change/@adaptive-web-adaptive-ui-e82ee743-0977-4df0-9922-cc67bae3b821.json, change/@adaptive-web-adaptive-web-components-0c4d7c77-d485-4550-91c3-93ac0004eb98.json, packages/adaptive-ui/docs/api-report.md, packages/adaptive-ui/src/color/recipe.ts, packages/adaptive-ui/src/design-tokens/color.ts, packages/adaptive-ui/src/design-tokens/layer.ts, packages/adaptive-ui/src/migration/color.ts, packages/adaptive-ui/src/modules/element-styles-renderer.ts, packages/adaptive-ui/src/modules/selector.ts, packages/adaptive-ui/src/modules/styles.ts, packages/adaptive-ui/src/modules/types.ts, packages/adaptive-ui/src/token-helpers-color.ts, packages/adaptive-ui/src/types.ts, packages/adaptive-web-components/src/components/breadcrumb-item/breadcrumb-item.styles.modules.ts, packages/adaptive-web-components/src/global.styles.modules.ts
Added support for overriding interactive state selectors in Adaptive UI
- Naming and type cleanup around interactive states
I dusted off the TypeScript manual for this one, but I think the type updates here are beneficial around the consolidation of what "interactive" means and the consistency of the handling of the states. Would love any feedback about any potential issues or alternatives.
Tested in AWC, including ad-hoc updates to validate style output with state overrides. I plan to add automated testing around this feature, but want to get the initial update pushed first.
Add automated testing around this area of the package.
=> Adaptive UI: Added support for overriding interactive state selectors

change/@adaptive-web-adaptive-ui-3ee37aaf-126b-435c-8f21-6b3e41ecc67b.json, change/@adaptive-web-adaptive-web-components-773cc7f3-c184-4004-935e-2efb19eea303.json, packages/adaptive-ui/docs/api-report.md, packages/adaptive-ui/src/core/modules/selector.ts, packages/adaptive-ui/src/core/modules/types.ts, packages/adaptive-web-components/docs/api-report.md, packages/adaptive-web-components/src/design-system.ts
AUI included an opinion/optimization that all `part` selectors were actually class names. This originated from that convention on the FAST Foundation template implementation. In expanding AUI capabilities to support other frameworks, this assumption is detrimental.
This PR removes the assumption from the underlying AUI code, but at least for the time being leaves it in AWC. We have other updates planned around the component Anatomy structure, including a naming strategy, so this capability will further improve, but since all AWC components are based on FAST Foundation now, it keeps the opinion and centralizes the necessary update.
The intent here was a least-touch PR that maintains existing opinions and functionality. As mentioned, we're planning to refactor this soon anyway,
Tested in …
=> AUI: Remove assumption on `part` selector

change/@adaptive-web-adaptive-ui-8394728e-6ae4-40e4-a0bc-9a0cbcb1171b.json, packages/adaptive-ui-figma-designer/src/core/code-gen.ts, packages/adaptive-ui/docs/api-report.md, packages/adaptive-ui/src/core/adaptive-design-tokens.ts, packages/adaptive-ui/src/core/modules/types.ts
- Updated code gen logic to remove some assumptions about how it might be consumed.
- Improved handing of different structures for anatomy conditions.
- Styles referenced by name for lookup rather than assumption of variable name.
- Added a registry for design tokens for lookup based on name.
There are a few interfaces and classes added for serialization. This is for a portion of work that generalizes the anatomy into json. We plan to immediately migrate the Figma-specific parsing logic to a new Figma-specific package, and soon after to refactor the AUI anatomy definition to better support both schema and TypeScript validation.
Tested in Figma plugin.
- Moving the code-gen capabilities into a new package for Figma-specific parsing logic.
- Refactoring AUI anatomy types.
=> Designer: Refactor code gen for more consumption use cases

change/@adaptive-web-adaptive-ui-designer-figma-c0e00d8c-c4ff-4895-bfa8-19cf6ec650f8.json, packages/adaptive-ui-designer-figma/src/cli/library-config.ts, packages/adaptive-ui-designer-figma/src/cli/main.ts, packages/adaptive-ui-designer-figma/src/cli/stylesheet.ts
The Designer CLI wasn't working on Windows, related to a shell script not executing correctly. Added a parameter that fixes this, but haven't tested on mac.
Added some error messaging since I was running into errors with my config but the messages weren't being displayed.
Open to suggestions on the error handling. I went for the least obtrusive solution I could find.
Tested on Windows. Please validate on mac.
=> Fixing a few CLI runtime issues

change/@adaptive-web-adaptive-ui-9a1613c3-c2e2-44c5-9a42-4cb2b5216378.json, change/@adaptive-web-adaptive-ui-designer-figma-44d25ed7-78a9-46a7-8518-788cb1ac9ca3.json, packages/adaptive-ui-designer-figma-plugin/src/core/code-gen.ts, packages/adaptive-ui-designer-figma/src/lib/anatomy.ts, packages/adaptive-ui/docs/api-report.md, packages/adaptive-ui/src/bin/aui.ts, packages/adaptive-ui/src/core/modules/types.ts
Aligning the naming and of the properties associated with a style rule. Originally in AUI these were "properties" but in the json anatomy we initially only supported token values so we called them "tokens". As we continue to reconcile the models it's better to call them the same thing.
Tested in AUI CLI.
=> AUI: Update CLI from `tokens` to align with existing `properties`

change/@adaptive-web-adaptive-ui-designer-core-a1d3a17c-d392-4dd1-ba4f-07204ba4b955.json, change/@adaptive-web-adaptive-ui-designer-figma-602338ac-be9f-4281-8f99-be2dd70df37e.json, packages/adaptive-ui-designer-core/src/index.ts, packages/adaptive-ui-designer-core/src/model.ts, packages/adaptive-ui-designer-core/src/node.ts, packages/adaptive-ui-designer-figma/src/lib/anatomy.ts, packages/adaptive-ui-designer-figma/src/lib/node-parser.ts
In Figma we often build components from smaller components. In some cases those are actual implemented components, like a Button, but sometimes they are just convenience for construction in Figma.
The `inline` configuration option added to a node here allows us to mark a component as a construction utility and "inline" it into the components where it's used for style processing. The concrete example of this is a Label component which has the label text node and a required indicator node. It's unlikely we will write an actual Label component, rather that this is just an attribute or slot of a handful of implemented components. We can now mark that inline and components like a Text Filed, Select, etc. will be able to process styling for the label elements.
The alternative is that the …
=> Designer: Added ability to mark a node `inline` for styling

change/@adaptive-web-adaptive-ui-0e754ad7-4d2d-4075-ab2d-064d314e21f6.json, change/@adaptive-web-adaptive-ui-designer-core-61534f82-7ad1-4cc3-827f-a773f0158229.json, change/@adaptive-web-adaptive-web-components-50a3cba4-cda8-41ad-ba24-024b430b1065.json, package-lock.json, packages/adaptive-ui-designer-core/src/node.ts, packages/adaptive-ui-designer-figma-plugin/package.json, packages/adaptive-ui-designer-figma-plugin/src/ui/app.ts, packages/adaptive-ui-designer-figma-plugin/src/ui/components/design-token-add/index.ts, packages/adaptive-ui-designer-figma-plugin/src/ui/components/stealth-button/index.ts, packages/adaptive-ui-designer-figma-plugin/src/ui/components/style-token-item/index.ts, packages/adaptive-ui-designer-figma-plugin/src/ui/components/token-glyph/index.ts, packages/adaptive-ui-designer-figma-plugin/src/ui/index.ts, packages/adaptive-ui-designer-figma-plugin/src/ui/tsconfig.json, packages/adaptive-ui-designer-figma-plugin/src/ui/ui-controller-code.ts, packages/adaptive-ui-designer-figma-plugin/src/ui/ui-controller-elements.ts, packages/adaptive-ui-designer-figma-plugin/src/ui/ui-controller-styles.ts, packages/adaptive-ui-designer-figma-plugin/src/ui/ui-controller-tokens.ts, packages/adaptive-ui-designer-figma-plugin/src/ui/ui-controller.ts, packages/adaptive-ui-explorer/src/app.ts, packages/adaptive-ui-explorer/src/components/adaptive-component.ts, packages/adaptive-ui-explorer/src/components/color-block.ts, packages/adaptive-ui-explorer/src/components/layer-background/index.ts, packages/adaptive-ui-explorer/src/components/swatch.ts, packages/adaptive-ui-explorer/src/state.ts, packages/adaptive-ui/docs/api-report.md, packages/adaptive-ui/src/core/adaptive-design-tokens.ts, packages/adaptive-ui/src/core/color/recipes/ideal-color-delta-swatch-set.spec.ts, packages/adaptive-web-components/src/components/menu-item/menu-item.ts, tsconfig.json
Paving the way to make future updates easier. Turned on `strict` across the entire repo.
The FAST web components require a lot of the observables and attributes to be optional and have a default value. I believe this PR makes the behavior more correct in what may actually happen, and thus some added checks make them more resilient.
Tested all leaf modules.
=> Turn on strict compilation mode

change/@adaptive-web-adaptive-ui-e0d5b689-bc54-4ebd-a792-599d0516bcb0.json, packages/adaptive-ui/docs/api-report.md, packages/adaptive-ui/src/core/color/palette-okhsl.ts, packages/adaptive-ui/src/core/token-helpers.ts, packages/adaptive-ui/src/reference/palette.ts
OK is the best algorithm we have for perceptual color, but the results are not always the intent we want in design. This PR adds some config options to the Okhsl palette:
- Allow customization of the number of steps in the palette, which is useful to increase or decrease contrast in the base design
- Set the saturation of the light and/or dark end to adjust the curve. Base colors with high saturation maintain that saturation even when the lightness is high, which makes them pop too much for some design intents.
Additive changes to the palette.
=> Adaptive UI: Added palette options for Okhsl

packages/adaptive-ui-designer-figma-plugin/src/figma/node.ts
Added support to the Figma Designer plugin for processing individual border token values.
Tested in Figma
=> Designer: Added support for individual border thickness

change/@adaptive-web-adaptive-ui-f8c4444f-eeae-489a-9d3d-8f84c8fc761b.json, packages/adaptive-ui/docs/api-report.md, packages/adaptive-ui/src/bin/aui.ts, packages/adaptive-ui/src/core/adaptive-design-tokens.ts, packages/adaptive-ui/src/core/token-helpers-color.ts
Added the ability to lookup a token group, which is the base of an interactive color recipe, for direct application to a part in a component anatomy definition.
My focus was too centered on the `Styles` (rules) capabilities to remember that the style processing code already handles Interactive Token Groups, all we needed was a way to look them up.
Tested in AUI Design-To-Code pipeline.
=> AUI: Add support for looking up Token Groups in anatomy

change/@adaptive-web-adaptive-ui-4e314a96-e352-46f2-b2ab-cfd816afe5fe.json, package-lock.json, packages/adaptive-ui/docs/api-report.md, packages/adaptive-ui/package.json, packages/adaptive-ui/src/bin/aui.ts, packages/adaptive-ui/src/core/modules/types.ts
Allows extracting common definitions shared across multiple components.
Initial example is adding success/error validation across all inputs.
- Can define those styles in one definition file
- Import that file in all input components
The deepmerge package seemed to be the most efficient way to merge the json docs, but open to suggestions.
Tested in AUI pipeline.
=> AUI: Add import capability to component anatomy definitions

change/@adaptive-web-adaptive-ui-designer-core-f48fe501-e71a-48f5-9eea-a0e138300aee.json, packages/adaptive-ui-designer-core/src/node.ts, packages/adaptive-ui-designer-figma-plugin/src/figma/node.ts, packages/adaptive-ui-designer-figma-plugin/src/ui/ui-controller-elements.ts, packages/adaptive-ui-designer-figma-plugin/src/ui/ui-controller.ts
I think I've finally resolved the issue where colors were being calculated incorrectly until you unselected and reselected a layer.
Cleaned up the handling of the effective fill color when you might have layers without a fill.
The key fix is in clearing the design token values in the shadow hierarchy at the right place so it's not latching old colors.
Tested in Figma Designer.
=> Designer: Fix parent fill color handling

.eslintrc.cjs, .eslintrc.json, change/@adaptive-web-adaptive-ui-designer-core-9aa2ae73-d413-4c28-8794-280f4d174fee.json, change/@adaptive-web-adaptive-ui-designer-figma-110f716f-d655-4696-8138-433516cc00d3.json, package-lock.json, package.json, packages/adaptive-ui-designer-core/package.json, packages/adaptive-ui-designer-core/src/controller.ts, packages/adaptive-ui-designer-core/src/model.ts, packages/adaptive-ui-designer-core/src/node.ts, packages/adaptive-ui-designer-figma-plugin/manifest.json, packages/adaptive-ui-designer-figma-plugin/package.json, packages/adaptive-ui-designer-figma-plugin/src/core/tsconfig.json, packages/adaptive-ui-designer-figma-plugin/src/figma/.eslintrc.json, packages/adaptive-ui-designer-figma-plugin/src/figma/controller.ts, packages/adaptive-ui-designer-figma-plugin/src/figma/main.ts, packages/adaptive-ui-designer-figma-plugin/src/figma/node.ts, packages/adaptive-ui-designer-figma/package.json
Figma has updated their Plugin API to be async. Updated the Designer to work with this new model.
As part of this they recommend using their eslint plugin. This turned out to be a lot of work to migrate to. I took the opportunity to get off of the deprecated FAST eslint rules.
=> Designer: Support Figma async page loading model

packages/adaptive-ui-designer-figma-plugin/src/ui/app.ts, packages/adaptive-ui-designer-figma-plugin/src/ui/components/design-token-add/index.ts, packages/adaptive-ui-designer-figma-plugin/src/ui/components/design-token-field/index.ts, packages/adaptive-ui-designer-figma-plugin/src/ui/components/design-tokens-form/index.ts, packages/adaptive-ui-designer-figma-plugin/src/ui/ui-controller-tokens.ts, packages/adaptive-ui-designer-figma-plugin/src/ui/util.ts
The DesignTokenDefinition and associated registry have been planned to phase out for a while. Now that all tokens are registered in AUI we no longer need it. This is not what I first set out to do, but it was a good checkpoint on the path.
Tested in Figma Designer
Continue updates to remove references to this.
=> Designer: Begin migration away from design token definition

change/@adaptive-web-adaptive-ui-a3f2c827-911c-4906-a735-78bd8f38bd99.json, change/@adaptive-web-adaptive-ui-designer-core-2547a09a-053d-486e-a3bf-3e015478db71.json, packages/adaptive-ui-designer-core/src/index.ts, packages/adaptive-ui-designer-core/src/registry/design-token-registry.ts, packages/adaptive-ui-designer-core/src/registry/recipes.ts, packages/adaptive-ui-designer-figma-plugin/src/ui/app.ts, packages/adaptive-ui-designer-figma-plugin/src/ui/components/style-token-item/index.ts, packages/adaptive-ui-designer-figma-plugin/src/ui/components/token-glyph/index.ts, packages/adaptive-ui-designer-figma-plugin/src/ui/ui-controller-elements.ts, packages/adaptive-ui-designer-figma-plugin/src/ui/ui-controller-styles.ts, packages/adaptive-ui-designer-figma-plugin/src/ui/ui-controller.ts, packages/adaptive-ui-designer-figma-plugin/src/ui/util.ts, packages/adaptive-ui/docs/api-report.md, packages/adaptive-ui/src/core/adaptive-design-tokens.ts, packages/adaptive-ui/src/core/modules/styles.ts, packages/adaptive-ui/src/core/types.ts, packages/adaptive-ui/src/reference/elevation.ts
Improved support for registering Interactive Token groups for use in design token properties.
Standardized some type information for groups.
Added support for applying interactive token groups directly as properties instead of only through styles (modules) as available previously.
I don't love the updates to get the token glyph preview to work in the plugin. I have some ideas to clean that up by turning the basic properties into the same `styles` format to ease the logic required to figure out what type of preview to show.
=> Designer: Added support for applying interactive groups

change/@adaptive-web-adaptive-ui-e17e5bd7-2c91-4d33-a2cf-7554ac72eb6a.json, packages/adaptive-ui/src/core/color/color.spec.ts, packages/adaptive-ui/src/core/color/swatch.spec.ts
Adding tests for all static and instance functions available on `Color` and `Swatch`.
Aside from having good tests, my motivation for this is for some refactoring work involving these classes. I want to make sure the resultant interfaces are equivalent but deprecated where necessary.
Ran tests.
As mentioned, I have some follow-up work to address some renaming and allow for new color features.
=> Add full tests for Color and Swatch classes

change/@adaptive-web-adaptive-ui-296ddcb4-ce1d-4ec7-80b5-106cc55a112b.json, packages/adaptive-ui-designer-figma-plugin/src/figma/controller.ts, packages/adaptive-ui-designer-figma-plugin/src/figma/main.ts, packages/adaptive-ui-designer-figma-plugin/src/ui/app.ts, packages/adaptive-ui/docs/api-report.md, packages/adaptive-ui/src/bin/aui.ts, packages/adaptive-ui/src/core/modules/element-styles-renderer.ts, packages/adaptive-ui/src/core/modules/types.ts
Fixed a bug in AUI style generation regarding where state selectors were placed.
Updated a performance option in the Designer plugin.
Tested in Designer plugin and AUI style generation.
=> AUI state bug fix
